
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Generate .env file
      run: |
          echo "DB_URI=${{ secrets.DB_URI }}" >> .env
          echo "JWT_KEY_TESTS=${{ secrets.JWT_KEY_TESTS }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "ROOT_API=${{ secrets.ROOT_API }}" >> .env
          echo "PRIVATE_KEY=a65715372eafc117d6dee10405748aa1ac13fe1d2e78edbc458787205a1e27a6" >> .env
          cp .env tests/
          ls -f
          cat .env
          # Add more lines for other secrets, following the same pattern
          #
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
